version: '3.8'

services:
  db_storage:
    image: mysql:8.0
    container_name: mysql_library_db_storage
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: storage_db
    ports:
      - "3306:3306"
    volumes:
      - db_storage_data:/var/lib/mysql

  db_tracker:
    image: mysql:8.0
    container_name: mysql_library_db_tracker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: tracker_db
    ports:
      - "3307:3306"
    volumes:
      - db_tracker_data:/var/lib/mysql

  db_auth:
    image: mysql:8.0
    container_name: mysql_library_db_auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auth_db
    ports:
      - "3308:3306"
    volumes:
      - db_auth_data:/var/lib/mysql
  flyway_storage:
    image: flyway/flyway
    command: -url=jdbc:mysql://db_storage:3306/storage_db?allowPublicKeyRetrieval=true -user=root -password=1234 -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./flyway/storage:/flyway/sql
    depends_on:
      - db_storage

  flyway_tracker:
    image: flyway/flyway
    command: -url=jdbc:mysql://db_tracker:3306/tracker_db?allowPublicKeyRetrieval=true -user=root -password=1234 -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./flyway/tracker:/flyway/sql
    depends_on:
      - db_tracker

  flyway_auth:
    image: flyway/flyway
    command: -url=jdbc:mysql://db_auth:3306/auth_db?allowPublicKeyRetrieval=true -user=root -password=1234 -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./flyway/auth:/flyway/sql
    depends_on:
      - db_auth

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db_storage_data:
  db_tracker_data:
  db_auth_data:
